theme: jekyll-theme-minimal
title: Resources on housing discrimination in the Berkeley Hills
description: A set of resources on the history of housing discrimination and redlining in the Berkeley Hills
